---
name: Run unit tests

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

# cancel any previously-started, yet still active runs of this workflow on the same branch
concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  go-test:
    name: Go Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: master

      - uses: actions/setup-go@v4
        with:
          go-version: 'stable'
        
      - name: Build
        id: dnb-build
        run: go mod tidy

      - name: Dual-N-Back test
        id: dnb-test
        run: go test -timeout 30s -v `go list ./... | grep -v wasm`
